apiVersion: v1
kind: Namespace
metadata:
  name: momentum

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: momentum-config
  namespace: momentum
data:
  DAILY_TASKS: "Task 1,Task 2,Task 3"

---
apiVersion: v1
kind: Service
metadata:
  namespace: momentum
  name: momentum-service
spec:
  type: ClusterIP 
  selector:
    app: momentum 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: momentum-pvc
  namespace: momentum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momentum-deployment
  namespace: momentum
  labels:
    app: momentum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: momentum
  template:
    metadata:
      labels:
        app: momentum
    spec:
      containers:
      - name: momentum
        image: ghcr.io/mitchfen/momentum:latest 
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: momentum-config
        volumeMounts:
        - name: momentum-data
          mountPath: /app/data
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "250m"
      volumes:
      - name: momentum-data
        persistentVolumeClaim:
          claimName: momentum-pvc
